paths:
  /api/search:
    post:
      summary: ルート一覧検索（取得） (SearchRoutes)
      operationId: SearchRoutes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                distance:
                  $ref: "../openapi.yaml#/components/schemas/RangeFloat"
                time:
                  $ref: "../openapi.yaml#/components/schemas/RangeInt"
                tags:
                  $ref: "../openapi.yaml#/components/schemas/TagArray"
                search_option:
                  $ref: "../openapi.yaml#/components/schemas/SearchOption"
                sort:
                  $ref: "../openapi.yaml#/components/schemas/Sort"
                limit:
                  $ref: "../openapi.yaml#/components/schemas/Limit"
      responses:
        "200":
          description: 成功
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  hit_count:
                    type: integer
                  routes:
                    type: array
                    items:
                      $ref: "../openapi.yaml#/components/schemas/RouteSummary"
                  # 受け取った検索条件のエコー
                  distance:
                    $ref: "../openapi.yaml#/components/schemas/RangeFloat"
                  time:
                    $ref: "../openapi.yaml#/components/schemas/RangeInt"
                  tags:
                    $ref: "../openapi.yaml#/components/schemas/TagArray"
                  search_option:
                    $ref: "../openapi.yaml#/components/schemas/SearchOption"
                  sort:
                    $ref: "../openapi.yaml#/components/schemas/Sort"
                  limit:
                    $ref: "../openapi.yaml#/components/schemas/Limit"
                  # エラー
                  error:
                    type: string
                    example: ""
        "400":
          description: 不正なリクエスト
        "500":
          description: サーバー内エラー

  /api/routes:
    post:
      summary: ルート詳細情報の作成 (PostRoute)
      operationId: PostRoute
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                $ref: "../openapi.yaml#/components/schemas/Route"
        "201":
          description: 作成成功
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  route_id:
                    $ref: "../openapi.yaml#/components/schemas/UUID"
                  update_at:
                    type: string
                    pattern: "^\\d{4}/\\d{2}/\\d{2}$"
                    example: "2024/04/21"
                  # 受け取った値のエコー
                  $ref: "../openapi.yaml#/components/schemas/Route"
                  # エラー
                  error:
                    type: string
                    example: ""
        "400":
          description: 不正なリクエスト
        "401":
          description: 未認証
        "500":
          description: サーバー内エラー

  /api/routes/{route_id}:
    get:
      summary: ルート詳細情報の取得 (GetRoute)
      operationId: GetRoute
      parameters:
        - name: route_id
          in: path
          required: true
          schema:
            $ref: "../openapi.yaml#/components/schemas/UUID"
      responses:
        "200":
          description: 成功
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  # 受け取った値のエコー
                   route_id:
                    $ref: "../openapi.yaml#/components/schemas/UUID"
                  # その他の値
                  update_at:
                    type: string
                    pattern: "^\\d{4}/\\d{2}/\\d{2}$"
                    example: "2024/04/21"
                  $ref: "../openapi.yaml#/components/schemas/Route"
                  # エラー
                  error:
                    type: string
                    example: ""
        "400":
          description: 不正なリクエスト
        "404":
          description: リソースが存在しない
        "500":
          description: サーバー内エラー
