paths:
  /api/search:
    post:
      summary: ルート一覧検索（取得） (SearchRoutes)
      operationId: SearchRoutes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                distance:
                  $ref: "../openapi.yaml#/components/schemas/RangeFloat"
                time:
                  $ref: "../openapi.yaml#/components/schemas/RangeInt"
                tags:
                  $ref: "../openapi.yaml#/components/schemas/TagArray"
                search_option:
                  $ref: "../openapi.yaml#/components/schemas/SearchOption"
                sort:
                  $ref: "../openapi.yaml#/components/schemas/Sort"
                limit:
                  $ref: "../openapi.yaml#/components/schemas/Limit"
      responses:
        "200":
          description: 成功
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  hit_count:
                    type: integer
                  routes:
                    type: array
                    items:
                      $ref: "../openapi.yaml#/components/schemas/RouteSummary"
                  ../openapi.yaml# 受け取った検索条件も返す
                  distance:
                    $ref: "../openapi.yaml#/components/schemas/RangeFloat"
                  time:
                    $ref: "../openapi.yaml#/components/schemas/RangeInt"
                  tags:
                    $ref: "../openapi.yaml#/components/schemas/TagArray"
                  search_option:
                    $ref: "../openapi.yaml#/components/schemas/SearchOption"
                  sort:
                    $ref: "../openapi.yaml#/components/schemas/Sort"
                  limit:
                    $ref: "../openapi.yaml#/components/schemas/Limit"
                  error:
                    type: string
                    example: ""
        "400":
          description: 不正なリクエスト
        "500":
          description: サーバー内エラー

  /api/routes:
    post:
      summary: ルート詳細情報の作成 (PostRoute)
      operationId: PostRoute
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 20
                description:
                  type: string
                  minLength: 1
                  maxLength: 60
                full_description:
                  type: string
                  minLength: 1
                  maxLength: 200
                distance:
                  type: number
                  format: double
                  minimum: 0.0
                time:
                  type: integer
                  minimum: 0
                tags:
                  $ref: "../openapi.yaml#/components/schemas/TagArray"
                total_checkpoints:
                  type: integer
                  minimum: 1
                  maximum: 20
                images:
                  type: array
                  items:
                    type: string
                    format: uri
                    minLength: 8
                    maxLength: 1023
                  minItems: 1
                  maxItems: 6
                map:
                  type: string
                  format: uri
                  minLength: 8
                  maxLength: 1023
                checkpoints:
                  type: array
                  items:
                    $ref: "../openapi.yaml#/components/schemas/Checkpoint"
      responses:
        "201":
          description: 作成成功
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  route_id:
                    $ref: "../openapi.yaml#/components/schemas/UUID"
                  update_at:
                    type: string
                    pattern: "^\\d{4}/\\d{2}/\\d{2}$"
                  ../openapi.yaml# 受け取った値のエコー
                  title:
                    type: string
                    minLength: 1
                    maxLength: 20
                  description:
                    type: string
                    minLength: 1
                    maxLength: 60
                  full_description:
                    type: string
                    minLength: 1
                    maxLength: 200
                  distance:
                    type: number
                    format: double
                    minimum: 0.0
                  time:
                    type: integer
                    minimum: 0
                  tags:
                    $ref: "../openapi.yaml#/components/schemas/TagArray"
                  total_checkpoints:
                    type: integer
                    minimum: 1
                    maximum: 20
                  images:
                    type: array
                    items:
                      type: string
                      format: uri
                  map:
                    type: string
                    format: uri
                  checkpoints:
                    type: array
                    items:
                      $ref: "../openapi.yaml#/components/schemas/Checkpoint"
                  error:
                    type: string
                    example: ""
        "400":
          description: 不正なリクエスト
        "401":
          description: 未認証
        "500":
          description: サーバー内エラー

  /api/routes/{route_id}:
    get:
      summary: ルート詳細情報の取得 (GetRoute)
      operationId: GetRoute
      parameters:
        - name: route_id
          in: path
          required: true
          schema:
            $ref: "../openapi.yaml#/components/schemas/UUID"
      responses:
        "200":
          description: 成功
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  route_id:
                    $ref: "../openapi.yaml#/components/schemas/UUID"
                  title:
                    type: string
                  description:
                    type: string
                  full_description:
                    type: string
                  distance:
                    type: number
                    format: double
                  time:
                    type: integer
                  tags:
                    $ref: "../openapi.yaml#/components/schemas/TagArray"
                  total_checkpoints:
                    type: integer
                  images:
                    type: array
                    items:
                      type: string
                      format: uri
                  map:
                    type: string
                    format: uri
                  update_at:
                    type: string
                    pattern: "^\\d{4}/\\d{2}/\\d{2}$"
                  checkpoints:
                    type: array
                    items:
                      $ref: "../openapi.yaml#/components/schemas/Checkpoint"
                  error:
                    type: string
                    example: ""
        "400":
          description: 不正なリクエスト
        "404":
          description: リソースが存在しない
        "500":
          description: サーバー内エラー
